use super::Logo;

// Mono-colour helper: every line gets the same colour prefix and a reset suffix.
macro_rules! mono {
    ($name:literal, $width:literal, $color:literal, [ $($line:literal,)* ]) => {
        Logo {
            name: $name,
            width: $width,
            lines: &[ $( concat!($color, $line, "\x1b[0m"), )* ],
        }
    };
}

// ANSI bold-colour escapes used directly inside `concat!` (only literals are
// accepted there, so naming them as `const` doesn't help — keeping them inline).
// Reference: 31 red, 32 green, 33 yellow, 34 blue, 35 magenta, 36 cyan, 37 white.

pub static ARCH: Logo = mono!("arch", 40, "\x1b[1;36m", [
    "                   -`                   ",
    "                  .o+`                  ",
    "                 `ooo/                  ",
    "                `+oooo:                 ",
    "               `+oooooo:                ",
    "               -+oooooo+:               ",
    "             `/:-:++oooo+:              ",
    "            `/++++/+++++++:             ",
    "           `/++++++++++++++:            ",
    "          `/+++ooooooooooooo/`          ",
    "         ./ooosssso++osssssso+`         ",
    "        .oossssso-````/ossssss+`        ",
    "       -osssssso.      :ssssssso.       ",
    "      :osssssss/        osssso+++.      ",
    "     /ossssssss/        +ssssooo/-      ",
    "   `/ossssso+/:-        -:/+osssso+-    ",
    "  `+sso+:-`                 `.-/+oso:   ",
    " `++:.                           `-/+/  ",
    " .`                                 `/  ",
]);

pub static UBUNTU: Logo = mono!("ubuntu", 42, "\x1b[1;31m", [
    "            .-/+oossssoo+/-.            ",
    "        `:+ssssssssssssssssss+:`        ",
    "      -+ssssssssssssssssssyyssss+-      ",
    "    .ossssssssssssssssssdMMMNysssso.    ",
    "   /ssssssssssshdmmNNmmyNMMMMhssssss/   ",
    "  +ssssssssshmydMMMMMMMNddddyssssssss+  ",
    " /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/ ",
    ".ssssssssdMMMNhsssssssssshNMMMdssssssss.",
    "+sssshhhyNMMNyssssssssssssyNMMMysssssss+",
    "ossyNMMMNyMMhsssssssssssssshmmmhssssssso",
    "ossyNMMMNyMMhsssssssssssssshmmmhssssssso",
    "+sssshhhyNMMNyssssssssssssyNMMMysssssss+",
    ".ssssssssdMMMNhsssssssssshNMMMdssssssss.",
    " /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/ ",
    "  +sssssssssdmydMMMMMMMMddddyssssssss+  ",
    "   /ssssssssssshdmNNNNmyNMMMMhssssss/   ",
    "    .ossssssssssssssssssdMMMNysssso.    ",
    "      -+sssssssssssssssssyyyssss+-      ",
    "        `:+ssssssssssssssssss+:`        ",
    "            .-/+oossssoo+/-.            ",
]);

pub static DEBIAN: Logo = mono!("debian", 36, "\x1b[1;31m", [
    "       _,met$$$$$gg.                ",
    "    ,g$$$$$$$$$$$$$$$P.             ",
    "  ,g$$P\"     \"\"\"Y$$.\".              ",
    " ,$$P'              `$$$.           ",
    "',$$P       ,ggs.     `$$b:         ",
    "`d$$'     ,$P\"'   .    $$$          ",
    " $$P      d$'     ,    $$P          ",
    " $$:      $$.   -    ,d$$'          ",
    " $$;      Y$b._   _,d$P'            ",
    " Y$$.    `.`\"Y$$$$P\"'               ",
    " `$$b      \"-.__                    ",
    "  `Y$$                              ",
    "   `Y$$.                            ",
    "     `$$b.                          ",
    "       `Y$$b.                       ",
    "          `\"Y$b._                   ",
    "              `\"\"\"\"                 ",
]);

pub static FEDORA: Logo = mono!("fedora", 40, "\x1b[1;34m", [
    "             .',;::::;,'.               ",
    "         .';:cccccccccccc;,.            ",
    "      .;cccccccccccccccccccccc;.        ",
    "    .:cccccccccccccccccccccccccc:.      ",
    "  .;ccccccccccccc;.:dddl:.;ccccccc;.    ",
    " .:ccccccccccccc;OWMKOOXMWd;ccccccc:.   ",
    ".:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.  ",
    ",cccccccccccccc;MMM.;cc;;WW::cccccccc,  ",
    ":cccccccccccccc;MMM.;cccccccccccccccc:  ",
    ":ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:  ",
    "cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;  ",
    "ccccc:XM0';cccc;MMM.;cccccccccccccccc'  ",
    "ccccc;MMo;ccccc;MMW.;ccccccccccccccc;   ",
    "ccccc;0MNc.ccc.xMMd:ccccccccccccccc;    ",
    "cccccc;dNMWXXXWM0::cccccccccccccc:,     ",
    "cccccccc;.:odl:.;cccccccccccccc:,.      ",
    " :cccccccccccccccccccccccccccc:'.       ",
    "  .:cccccccccccccccccccccc:;,..         ",
    "    '::cccccccccccccc::;,.              ",
]);

pub static MINT: Logo = mono!("mint", 45, "\x1b[1;32m", [
    " MMMMMMMMMMMMMMMMMMMMMMMMMmds+.              ",
    " MMm----::-://////////////oymNMd+`           ",
    " MMd      /++                -sNMd:          ",
    " MMNso/`  dMM    `.::-. .-::.` .hMN:         ",
    " ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm         ",
    "     NMm  dMM  .NMN/-+MMM+-/NMN` dMM         ",
    "     NMm  dMM  -MMm  `MMM   dMM. dMM         ",
    "     NMm  dMM  -MMm  `MMM   dMM. dMM         ",
    "     NMm  dMM  .mmd  `mmm   yMM. dMM         ",
    "     NMm  dMM`  ..`   ...   ydm. dMM         ",
    "     hMM- +MMd/-------...-:sdds  dMM         ",
    "     -NMm- :hNMNNNmdddddddddy/`  dMM         ",
    "      -dMNs-``-::::-------.``    dMM         ",
    "       `/dMNmy+/:-------------:/yMMM         ",
    "          ./ydNMMMMMMMMMMMMMMMMMMMMM         ",
    "             \\.MMMMMMMMMMMMMMMMMMM           ",
]);

pub static POP: Logo = mono!("pop", 42, "\x1b[1;36m", [
    "             /////////////                ",
    "         /////////////////////            ",
    "      ///////*766666666@//////////        ",
    "    //////////////////////////////        ",
    "   ///////////////////////////////        ",
    "  ////////////////666@//////////////      ",
    " ///////////**6666666@///////////////     ",
    "/////////***66666666@//////////////////   ",
    "/////////*##666@*****/////////////////    ",
    "/////////////////**######/////////////    ",
    "//////////////**###%%%%%%////////////     ",
    " ///////////**####%%%%%%%%%%%////////     ",
    "  /////////####%%%%%%%%%%@@@@///////      ",
    "   ///////##%%%%%%@@@@@@@@@/////////      ",
    "    //////%%%%%@@@@@@@@@@//////////       ",
    "      //////@@@@@@@@@//////////           ",
    "         /////////////////////            ",
    "             /////////////                ",
]);

pub static MANJARO: Logo = mono!("manjaro", 32, "\x1b[1;32m", [
    "██████████████████  ████████   ",
    "██████████████████  ████████   ",
    "██████████████████  ████████   ",
    "██████████████████  ████████   ",
    "████████            ████████   ",
    "████████  ████████  ████████   ",
    "████████  ████████  ████████   ",
    "████████  ████████  ████████   ",
    "████████  ████████  ████████   ",
    "████████  ████████  ████████   ",
    "████████  ████████  ████████   ",
    "████████  ████████  ████████   ",
    "████████  ████████  ████████   ",
    "████████  ████████  ████████   ",
]);

pub static OPENSUSE: Logo = mono!("opensuse", 42, "\x1b[1;32m", [
    "           .;ldkO0000Okdl;.               ",
    "       .;d00xl:^''''''^:ok00d;.           ",
    "     .d00l'                'o00d.         ",
    "   .d0Kd' Okxol:;,.          :O0d.        ",
    "  .OK KKK0kOKKKKKKKKKKOxo:,      lKO.     ",
    " ,0K KKKKKKKKKKKKKKK0P^,,,^dx:    ;00,    ",
    ".OK KKKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.   ",
    ":KK KKKKKKKKKKKKKKK: kKx..dd lKd    'OK:  ",
    "dKK KKKKKKKKKKKKKKKKKO. xK..00KKKKKKKKKK0 ",
    "dKK KKKKKKKKKKKKKKKKKKKKKKK 'OK XMMMMMMMM ",
    ":KK KKKKKKKKKKKKKKKKKKKKKKK  dKx'kMMMMMMM ",
    " kKK KKKKKKKKKKKKKKKKKKKKKKK..dkd.:MMMMMMM",
    " 'OK KKKKKKKKKKKKKKKKKKKKKKKKK.cuuyy.YMMM ",
    "  '0K KKKKKKKKKKKKKKKKKKKKKKKKKKK.    OMM ",
    "   'kK KKOxddxkOO0000Okxoc;'        ,0M   ",
    "     l0Kk.                  .;ck00d.      ",
    "      `lO0xc.            ,:lkO0o`         ",
    "         ,:ldxkOOO000OOkxoc;.             ",
]);

pub static ALPINE: Logo = mono!("alpine", 36, "\x1b[1;34m", [
    "       .hddddddddddddddddddddddh.   ",
    "      :dddddddddddddddddddddddddd:  ",
    "     /dddddddddddddddddddddddddddd/ ",
    "    +dddddddddddddddddddddddddddddd+",
    "  `sdddddddddddddddddddddddddddddddds",
    " `ydddddddddddd++hdddddddddddddddddddy",
    ".hddddddddddd+`  `+ddddh:-sdddddddddh.",
    "hdddddddddd+`      `+y:    .sddddddddh",
    "ddddddddh+`   `//`   `.`     -sddddddd",
    "ddddddh+`   `/hddh/`   `:s-    -sddddd",
    "ddddh+`   `/+/dddddh/`   `+s-    -sddd",
    "ddd+`   `/o` :dddddddh/`   `oy-    -sd",
    "+`   `/sy.   .yddddddddh/`   `+ys-   `",
    "    /yhyo`    .hddddddddddh:`  `oyy/  ",
    "   /y/ `+sso`  -hdddddddddddh+. `sh/  ",
    "  -y- `+ssso`   .ddddddddddddh+. `o-  ",
    "      `osss/     -ddddddddddddh+`     ",
]);

pub static NIXOS: Logo = Logo {
    name: "nixos",
    width: 40,
    lines: &[
        concat!("\x1b[1;34m", "          ::::.    ", "\x1b[1;36m", "':::::     ::::'          ", "\x1b[0m"),
        concat!("\x1b[1;34m", "          ':::::    ", "\x1b[1;36m", "':::::.  ::::'           ", "\x1b[0m"),
        concat!("\x1b[1;34m", "            :::::     ", "\x1b[1;36m", "'::::.:::::            ", "\x1b[0m"),
        concat!("\x1b[1;34m", "      .......:::::..... ", "\x1b[1;36m", "::::::::             ", "\x1b[0m"),
        concat!("\x1b[1;34m", "     ::::::::::::::::::. ", "\x1b[1;36m", "::::::    ", "\x1b[1;34m", "::::.       ", "\x1b[0m"),
        concat!("\x1b[1;34m", "    ::::::::::::::::::::: ", "\x1b[1;36m", ":::::.  ", "\x1b[1;34m", ".::::'       ", "\x1b[0m"),
        concat!("\x1b[1;36m", "           .....           ", "\x1b[1;34m", "::::' ", "\x1b[1;36m", ":::::'        ", "\x1b[0m"),
        concat!("\x1b[1;36m", "          :::::            ", "\x1b[1;34m", "'::' ", "\x1b[1;36m", ":::::'         ", "\x1b[0m"),
        concat!("\x1b[1;36m", " ........:::::               ", "\x1b[1;34m", "' ", "\x1b[1;36m", ":::::::::::.   ", "\x1b[0m"),
        concat!("\x1b[1;36m", ":::::::::::::                 ", "\x1b[1;34m", ":::::::::::::   ", "\x1b[0m"),
        concat!("\x1b[1;36m", " ::::::::::: ", "\x1b[1;34m", "..              ", "\x1b[1;36m", ":::::            ", "\x1b[0m"),
        concat!("\x1b[1;36m", "     .::::: ", "\x1b[1;34m", ".:::            ", "\x1b[1;36m", ":::::             ", "\x1b[0m"),
        concat!("\x1b[1;36m", "    .:::::  ", "\x1b[1;34m", ":::::          ", "\x1b[1;36m", "'''''    ", "\x1b[1;34m", ".....       ", "\x1b[0m"),
        concat!("\x1b[1;36m", "    :::::   ", "\x1b[1;34m", "':::::.  ", "\x1b[1;36m", "......:::::::::::::'      ", "\x1b[0m"),
        concat!("\x1b[1;36m", "     :::     ", "\x1b[1;34m", "::::::. ", "\x1b[1;36m", "':::::::::::::::::'       ", "\x1b[0m"),
        concat!("\x1b[1;34m", "            .:::::::: ", "\x1b[1;36m", "'::::::::::                ", "\x1b[0m"),
        concat!("\x1b[1;34m", "           .::::''::::.     ", "\x1b[1;36m", "'::::.                ", "\x1b[0m"),
        concat!("\x1b[1;34m", "          .::::'   ::::.     ", "\x1b[1;36m", "'::::.               ", "\x1b[0m"),
        concat!("\x1b[1;34m", "         .::::      ::::      ", "\x1b[1;36m", "'::::.              ", "\x1b[0m"),
    ],
};

pub static ENDEAVOUROS: Logo = mono!("endeavouros", 40, "\x1b[1;35m", [
    "                     ./o.                ",
    "                   ./sssso-               ",
    "                 `:osssssss+-             ",
    "               `:+sssssssssso+:`          ",
    "             `-/ossssssssssssso/.         ",
    "           `-/+sssssssssssssssso+:`       ",
    "         `-:/+sssssssssssssssssso+/.      ",
    "       `.://osssssssssssssssssssso++-     ",
    "      .://+ssssssssssssssssssssssso++:    ",
    "    .:///ossssssssssssssssssssssssso++:   ",
    "  `:////ssssssssssssssssssssssssssso+++.  ",
    "`-////+ssssssssssssssssssssssssssso++++-  ",
    " `..-+oosssssssssssssssssssssssso+++++/`  ",
    "   ./++++++++++++++++++++++++++++++/:.    ",
    "  `:::::::::::::::::::::::::------``      ",
]);

pub static ARTIX: Logo = mono!("artix", 40, "\x1b[1;36m", [
    "                   '                    ",
    "                  'o'                   ",
    "                 'ooo'                  ",
    "                'ooxoo'                 ",
    "               'ooxxxoo'                ",
    "              'oookkxxoo'               ",
    "             'oiioxkkxxoo'              ",
    "            ':;:iiiioxxxoo'             ",
    "               `'.;::ioxxoo'            ",
    "          '-.      `':;jiooo'           ",
    "         'oooio-..      `'i:io'         ",
    "        'ooooxxxxoio:,.    `'-;'        ",
    "       'ooooxxxxxkkxoooIi:-.  `'        ",
    "      'ooooxxxxxkkkkxoiiiiiji'          ",
    "     'ooooxxxxxkxxoiiii:'`     .i'      ",
    "    'ooooxxxxxoi:::'`       .;ioxo'     ",
    "   'ooooxooi::'`         .:iiixkxxo'    ",
    "  'ooooi:'`                `'';ioxxo'   ",
    " 'i:'`                          '':io'  ",
    "'`                                   `'  ",
]);

pub static GENTOO: Logo = mono!("gentoo", 38, "\x1b[1;35m", [
    "         -/oyddmdhs+:.                ",
    "     -o+ +//ydNMMMMNNhho/.            ",
    "   -yh+`./+ +oyysshhMMMMMMNhh+        ",
    " `/yhsds+oo--`     -hNMMMMMMMNh+      ",
    "`/yNMMMMmsuydsoo+yyhhsdNMMMMMmdyo`    ",
    "-yNMMMMMNNNNNNNNNNNNNNNNMMMMMMMMddl   ",
    " yMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMs   ",
    " -NMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMy   ",
    "  hMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMd    ",
    "  -NMMMMNNMMMMMMMMMMMMMMMMMMMMMMM-    ",
    "   sMMMMMMMMMMMMMMMMMMMMMMMMMMMm`     ",
    "   /NMMMMMMMMMMMMMMMMMMMMMMMMMs       ",
    "    +MMMMMMMMMMMMMMMMMMMMMMMd-        ",
    "     /yMMMMMMMMMMMMMMMMMMMs-          ",
    "      `:smMMMMMMMMMMMMNo-             ",
    "         `-/+oosshNh+:`               ",
]);

pub static VOID: Logo = mono!("void", 38, "\x1b[1;32m", [
    "                __.;=====;.__         ",
    "            _.=+==++=====+=.._        ",
    "         .-=:`               `::-.    ",
    "      .=+;-          _.=ng:_   ;+=.   ",
    "    .:t- `.=+ggsxxxxxgggssg+.    -i:  ",
    "   ;: `lggsxttitxtittxtitiggi.    .;; ",
    "  ;` :ti :::    :::::    :: ti.     .;",
    " :  it :: t   t  :: ti   ti :ti      :",
    " :  iy ::      :      ::    : :it    .",
    " :  :y;: :i:..t      .;ii:.. :   t   .",
    " ;   :y;,,'`````,,;ii:,,,'`````,,;  ;.",
    "  ;   ;tt;;,,;;;;;ii;;;,,;;;;;ttt; .` ",
    "   ;:   :tttttttttttttttttttttt:   :: ",
    "    .::    :ttttttttttttttttt:   :.   ",
    "      .:::.   `:tttttttttt:` .::-     ",
    "         `-::._         _.:--`        ",
    "             `--========--`           ",
]);

pub static KALI: Logo = mono!("kali", 40, "\x1b[1;34m", [
    "..............                          ",
    "            ..,;:ccc,.                  ",
    "          ......''';lxO.                ",
    ".....''''..........,:ld;                ",
    "           .';;;:::;,,.x,               ",
    "      ..'''.            0Xxoc:,.  ...   ",
    "  ....                ,ONkc;,;cokOdc',. ",
    " .                   OMo           ':ddo",
    "                    dMc               :OO",
    "                    0M.                 .:o",
    "                    ;Wd                    ",
    "                     ;XO,                  ",
    "                       ,d0Odlc;,..         ",
    "                           ..',;:cdOOd::,. ",
    "                                    .:d;.':;.",
    "                                       'd,  .'",
    "                                         ;l   ..",
    "                                          .o    ",
    "                                            c   ",
]);

pub static MACOS: Logo = Logo {
    name: "macos",
    width: 38,
    lines: &[
        "\x1b[1;32m                    'c.                \x1b[0m",
        "\x1b[1;32m                 ,xNMM.                \x1b[0m",
        "\x1b[1;32m               .OMMMMo                 \x1b[0m",
        "\x1b[1;32m               OMMM0,                  \x1b[0m",
        "\x1b[1;32m     .;loddo:' loolloddol;.            \x1b[0m",
        "\x1b[1;32m   cKMMMMMMMMMMNWMMMMMMMMMM0:          \x1b[0m",
        "\x1b[1;33m .KMMMMMMMMMMMMMMMMMMMMMMMWd.          \x1b[0m",
        "\x1b[1;33m XMMMMMMMMMMMMMMMMMMMMMMMX.            \x1b[0m",
        "\x1b[1;31m;MMMMMMMMMMMMMMMMMMMMMMMM:             \x1b[0m",
        "\x1b[1;31m:MMMMMMMMMMMMMMMMMMMMMMMM:             \x1b[0m",
        "\x1b[1;31m.MMMMMMMMMMMMMMMMMMMMMMMMX.            \x1b[0m",
        "\x1b[1;31m kMMMMMMMMMMMMMMMMMMMMMMMMWd.          \x1b[0m",
        "\x1b[1;35m 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk          \x1b[0m",
        "\x1b[1;35m  'XMMMMMMMMMMMMMMMMMMMMMMMMK.         \x1b[0m",
        "\x1b[1;34m    kMMMMMMMMMMMMMMMMMMMMMMd            \x1b[0m",
        "\x1b[1;34m     ;KMMMMMMMWXXWMMMMMMMk.             \x1b[0m",
        "\x1b[1;34m       .cooc,.    .,coo:.               \x1b[0m",
    ],
};

pub static WINDOWS: Logo = Logo {
    name: "windows",
    width: 40,
    lines: &[
        "\x1b[1;31m        ,.=:!!t3Z3z.,                  \x1b[0m",
        "\x1b[1;31m       :tt:::tt333EE3                  \x1b[0m",
        concat!("\x1b[1;31m", "       Et:::ztt33EEEL", "\x1b[1;32m", " @Ee.,      ..,", "\x1b[0m"),
        concat!("\x1b[1;31m", "      ;tt:::tt333EE7", "\x1b[1;32m", " ;EEEEEEttttt33#", "\x1b[0m"),
        concat!("\x1b[1;31m", "     :Et:::zt333EEQ.", "\x1b[1;32m", " $EEEEEttttt33QL", "\x1b[0m"),
        concat!("\x1b[1;31m", "     it::::tt333EEF", "\x1b[1;32m", " @EEEEEEttttt33F ", "\x1b[0m"),
        concat!("\x1b[1;31m", "    ;3=*^```\"*4EEV", "\x1b[1;32m", " :EEEEEEttttt33@. ", "\x1b[0m"),
        concat!("\x1b[1;34m", "    ,.=::::!t=., ", "\x1b[1;31m", "`", "\x1b[1;32m", " @EEEEEEtttz33QF  ", "\x1b[0m"),
        concat!("\x1b[1;34m", "   ;::::::::zt33)", "\x1b[1;32m", "   \"4EEEtttji3P*    ", "\x1b[0m"),
        concat!("\x1b[1;34m", "  :t::::::::tt33.", "\x1b[1;33m", ":Z3z..", "\x1b[1;32m", " ``", "\x1b[1;33m", " ,..g.       ", "\x1b[0m"),
        concat!("\x1b[1;34m", "  i::::::::zt33F", "\x1b[1;33m", " AEEEtttt::::ztF       ", "\x1b[0m"),
        concat!("\x1b[1;34m", " ;:::::::::t33V", "\x1b[1;33m", " ;EEEttttt::::t3        ", "\x1b[0m"),
        concat!("\x1b[1;34m", " E::::::::zt33L", "\x1b[1;33m", " @EEEtttt::::z3F        ", "\x1b[0m"),
        concat!("\x1b[1;34m", "{3=*^```\"*4E3)", "\x1b[1;33m", " ;EEEtttt:::::tZ`        ", "\x1b[0m"),
        concat!("\x1b[1;34m", "             `", "\x1b[1;33m", " :EEEEtttt::::z7         ", "\x1b[0m"),
        "\x1b[1;33m                 \"VEzjt:;;z>*`          \x1b[0m",
    ],
};

pub static TUX: Logo = mono!("tux", 30, "\x1b[1;37m", [
    "         #####                ",
    "        #######               ",
    "        ##O#O##               ",
    "        #######               ",
    "      ###########             ",
    "     #############            ",
    "    ###############           ",
    "    ################          ",
    "   ##################         ",
    "   ##################         ",
    "    ################          ",
    "      ############            ",
    "       ##########             ",
    "        ########              ",
    "        ########              ",
    "         ######               ",
]);
